/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                accessToken: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    createdAt: string;
                                };
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                accessToken: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    createdAt: string;
                                };
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                createdAt: string;
                            } | null;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                createdAt: string;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                    q?: string;
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                            }[];
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        magnet: string;
                        /** @default false */
                        pinned?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    deleteFiles?: "true" | "false";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: Record<string, never>[];
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/unpin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description SSE stream: `stats` (global), `torrents` (list deltas), `removed`. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PublicUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            createdAt: string;
        };
        Torrent: {
            /** Format: uuid */
            id: string;
            infoHash: string;
            name: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
            qbtState: string | null;
            progress: number;
            dlSpeedBps: number;
            upSpeedBps: number;
            etaSeconds: number | null;
            seedsConnected: number;
            seedsTotal: number;
            peersConnected: number;
            peersTotal: number;
            ratio: number;
            availability: number;
            downloadedBytes: number;
            uploadedBytes: number;
            pinned: boolean;
            addedAt: string;
            completedAt: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
