/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List a directory under the downloads root. Path is containment- and symlink-checked. */
        get: {
            parameters: {
                query?: {
                    path?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Directory listing */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: Record<string, never>;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/browse/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mint a download link for a browsed file. */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Link created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: Record<string, never>;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/browse/zip-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mint a streamed-zip link for a folder. */
        get: {
            parameters: {
                query: {
                    path: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Link created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: Record<string, never>;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Mint a short-lived download URL served directly by Caddy. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Link created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** @example /dl/eyJhbGci…/Big%20Buck%20Bunny.mp4 */
                                url: string;
                                /** @description Fully qualified — what the copy buttons hand out. */
                                absoluteUrl: string;
                                filename: string;
                                sizeBytes: number;
                                expiresAt: string;
                                /** @description Ready-to-paste 16-connection download command. */
                                aria2c: string;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        priority: number;
                    };
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: uuid */
                                torrentId: string;
                                qbtIndex: number;
                                path: string;
                                sizeBytes: number;
                                progress: number;
                                priority: number;
                                isComplete: boolean;
                                contentType: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Authenticated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                accessToken: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    createdAt: string;
                                };
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Rotated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                accessToken: string;
                                user: {
                                    /** Format: uuid */
                                    id: string;
                                    /** Format: email */
                                    email: string;
                                    createdAt: string;
                                };
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                createdAt: string;
                            } | null;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                /** Format: email */
                                email: string;
                                createdAt: string;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                    q?: string;
                    limit?: number;
                    offset?: number | null;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                                lastAccessedAt: string | null;
                                wastedBytes: number;
                                timeActiveSeconds: number;
                                seedingTimeSeconds: number;
                                lastActivityAt: string | null;
                                savePath: string | null;
                                contentPath: string | null;
                                category: string | null;
                                isPrivate: boolean;
                                piecesHave: number;
                                piecesNum: number;
                                pieceSizeBytes: number | null;
                                comment: string | null;
                                createdByClient: string | null;
                                trackerHost: string | null;
                                trackersCount: number;
                                errorMessage: string | null;
                            }[];
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        magnet: string;
                        /** @default false */
                        pinned?: boolean;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                                lastAccessedAt: string | null;
                                wastedBytes: number;
                                timeActiveSeconds: number;
                                seedingTimeSeconds: number;
                                lastActivityAt: string | null;
                                savePath: string | null;
                                contentPath: string | null;
                                category: string | null;
                                isPrivate: boolean;
                                piecesHave: number;
                                piecesNum: number;
                                pieceSizeBytes: number | null;
                                comment: string | null;
                                createdByClient: string | null;
                                trackerHost: string | null;
                                trackersCount: number;
                                errorMessage: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload a .torrent file (multipart/form-data, field `torrent`). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        torrent: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                                lastAccessedAt: string | null;
                                wastedBytes: number;
                                timeActiveSeconds: number;
                                seedingTimeSeconds: number;
                                lastActivityAt: string | null;
                                savePath: string | null;
                                contentPath: string | null;
                                category: string | null;
                                isPrivate: boolean;
                                piecesHave: number;
                                piecesNum: number;
                                pieceSizeBytes: number | null;
                                comment: string | null;
                                createdByClient: string | null;
                                trackerHost: string | null;
                                trackersCount: number;
                                errorMessage: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add up to 50 magnets at once. Each item reports its own outcome. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        magnets: string[];
                    };
                };
            };
            responses: {
                /** @description Batch complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                results: {
                                    /** @description Truncated for display; never the full magnet. */
                                    input: string;
                                    /** @enum {string} */
                                    status: "added" | "duplicate" | "failed";
                                    id: string | null;
                                    name: string | null;
                                    error: string | null;
                                }[];
                                added: number;
                                duplicates: number;
                                failed: number;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Upload several .torrent files at once (field `torrents`). */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch complete */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                results: {
                                    /** @description Truncated for display; never the full magnet. */
                                    input: string;
                                    /** @enum {string} */
                                    status: "added" | "duplicate" | "failed";
                                    id: string | null;
                                    name: string | null;
                                    error: string | null;
                                }[];
                                added: number;
                                duplicates: number;
                                failed: number;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: {
                                /** Format: uuid */
                                id: string;
                                infoHash: string;
                                name: string;
                                sizeBytes: number;
                                /** @enum {string} */
                                status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
                                qbtState: string | null;
                                progress: number;
                                dlSpeedBps: number;
                                upSpeedBps: number;
                                etaSeconds: number | null;
                                seedsConnected: number;
                                seedsTotal: number;
                                peersConnected: number;
                                peersTotal: number;
                                ratio: number;
                                availability: number;
                                downloadedBytes: number;
                                uploadedBytes: number;
                                pinned: boolean;
                                addedAt: string;
                                completedAt: string | null;
                                lastAccessedAt: string | null;
                                wastedBytes: number;
                                timeActiveSeconds: number;
                                seedingTimeSeconds: number;
                                lastActivityAt: string | null;
                                savePath: string | null;
                                contentPath: string | null;
                                category: string | null;
                                isPrivate: boolean;
                                piecesHave: number;
                                piecesNum: number;
                                pieceSizeBytes: number | null;
                                comment: string | null;
                                createdByClient: string | null;
                                trackerHost: string | null;
                                trackersCount: number;
                                errorMessage: string | null;
                            };
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: {
                    deleteFiles?: "true" | "false";
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: Record<string, never>[];
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/pin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/unpin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description SSE stream: `stats` (global), `torrents` (list deltas), `removed`. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/torrents/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Per-torrent SSE: `properties`, `peers`, `trackers`, `pieces`. Polling for this torrent starts when the first client connects and stops when the last disconnects. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            success: boolean;
                            message: string;
                            responseObject?: unknown;
                            statusCode: number;
                            code?: string;
                            requestId?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        File: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            torrentId: string;
            qbtIndex: number;
            path: string;
            sizeBytes: number;
            progress: number;
            priority: number;
            isComplete: boolean;
            contentType: string | null;
        };
        DownloadLink: {
            /** @example /dl/eyJhbGci…/Big%20Buck%20Bunny.mp4 */
            url: string;
            /** @description Fully qualified — what the copy buttons hand out. */
            absoluteUrl: string;
            filename: string;
            sizeBytes: number;
            expiresAt: string;
            /** @description Ready-to-paste 16-connection download command. */
            aria2c: string;
        };
        PublicUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            createdAt: string;
        };
        Torrent: {
            /** Format: uuid */
            id: string;
            infoHash: string;
            name: string;
            sizeBytes: number;
            /** @enum {string} */
            status: "queued" | "downloading" | "paused" | "completed" | "errored" | "evicted";
            qbtState: string | null;
            progress: number;
            dlSpeedBps: number;
            upSpeedBps: number;
            etaSeconds: number | null;
            seedsConnected: number;
            seedsTotal: number;
            peersConnected: number;
            peersTotal: number;
            ratio: number;
            availability: number;
            downloadedBytes: number;
            uploadedBytes: number;
            pinned: boolean;
            addedAt: string;
            completedAt: string | null;
            lastAccessedAt: string | null;
            wastedBytes: number;
            timeActiveSeconds: number;
            seedingTimeSeconds: number;
            lastActivityAt: string | null;
            savePath: string | null;
            contentPath: string | null;
            category: string | null;
            isPrivate: boolean;
            piecesHave: number;
            piecesNum: number;
            pieceSizeBytes: number | null;
            comment: string | null;
            createdByClient: string | null;
            trackerHost: string | null;
            trackersCount: number;
            errorMessage: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
