import cookieParser from "cookie-parser";
import cors from "cors";
import express, { type Express } from "express";
import helmet from "helmet";
import { openAPIRouter } from "@/api-docs/openAPIRouter";
import errorHandler from "@/common/middleware/errorHandler";
import rateLimiter from "@/common/middleware/rateLimiter";
import requestLogger from "@/common/middleware/requestLogger";
import { ServiceResponse } from "@/common/models/serviceResponse";
import { env } from "@/common/utils/envConfig";
import { handleServiceResponse } from "@/common/utils/httpHandlers";
import { logger } from "@/common/utils/logger";
import { authRouter } from "@/modules/auth/authRouter";
import { eventRouter } from "@/modules/event/eventRouter";
import { fileRouter } from "@/modules/file/fileRouter";
import { zipRouter } from "@/modules/file/zipRouter";
import { healthCheckRouter } from "@/modules/healthCheck/healthCheckRouter";
import { internalRouter } from "@/modules/internal/internalRouter";
import { settingsRouter } from "@/modules/settings/settingsRouter";
import { publicShareRouter, shareRouter } from "@/modules/share/shareRouter";
import { storageRouter } from "@/modules/storage/storageRouter";
import { systemRouter } from "@/modules/system/systemRouter";
import { torrentRouter } from "@/modules/torrent/torrentRouter";

const app: Express = express();

// Behind Caddy.
app.set("trust proxy", true);

app.use(express.json({ limit: "1mb" }));
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use(cors({ origin: env.CORS_ORIGIN, credentials: true }));
app.use(helmet());
app.use(requestLogger);
app.use(rateLimiter);

// Routes
app.use("/health-check", healthCheckRouter);
app.use("/api/v1/auth", authRouter);
app.use("/api/v1/torrents", torrentRouter);
app.use("/api/v1/files", fileRouter);
app.use("/api/v1/storage", storageRouter);
app.use("/api/v1/shares", shareRouter);
// Public share endpoints — deliberately NOT under the authenticated router.
app.use("/api/v1/public/shares", publicShareRouter);
app.use("/api/v1/settings", settingsRouter);
app.use("/api/v1/system", systemRouter);

// Internal only — never proxied by Caddy. See internalRouter.ts.
app.use("/internal", internalRouter);

// Folder downloads. Token-authenticated like /dl, but generated by Node because
// a zip cannot be served from disk by Caddy.
app.use("/zip", zipRouter);
app.use("/api/v1/events", eventRouter);

// API docs.
//
// Mounted at an EXPLICIT path, not the root. The boilerplate mounted it as
// `app.use(openAPIRouter)` with `swaggerUi.serve` on "/", which made it a
// catch-all: every unmatched path — `/api/v1/nope`, `/zip/`, anything — returned
// 200 with the Swagger HTML instead of a 404. A client could not distinguish
// "no such route" from success.
//
// Docs are also dev-only. There is one user; publishing a live map of the API
// surface to the internet buys nothing.
if (env.NODE_ENV !== "production") {
	app.use("/docs", openAPIRouter);
}

// Anything unmatched is a 404, in the same envelope as every other response.
app.use((req, res) => {
	handleServiceResponse(
		ServiceResponse.failure(`No route for ${req.method} ${req.path}`, null, 404, "RESOURCE_NOT_FOUND"),
		res,
	);
});

app.use(errorHandler());

export { app, logger };
