import { StatusCodes } from "http-status-codes";

/** Doc 03 §A4. The client switches on these, never on `message`. */
export const ErrorCode = {
	VALIDATION_ERROR: StatusCodes.BAD_REQUEST,

	AUTHENTICATION_REQUIRED: StatusCodes.UNAUTHORIZED,
	INVALID_CREDENTIALS: StatusCodes.UNAUTHORIZED,
	INVALID_TOKEN: StatusCodes.UNAUTHORIZED,
	TOKEN_EXPIRED: StatusCodes.UNAUTHORIZED,
	REFRESH_TOKEN_REUSED: StatusCodes.UNAUTHORIZED,

	PERMISSION_DENIED: StatusCodes.FORBIDDEN,
	SHARE_REVOKED: StatusCodes.FORBIDDEN,
	SHARE_PASSWORD_REQUIRED: StatusCodes.FORBIDDEN,

	RESOURCE_NOT_FOUND: StatusCodes.NOT_FOUND,
	SHARE_EXPIRED: StatusCodes.NOT_FOUND,

	TORRENT_ALREADY_EXISTS: StatusCodes.CONFLICT,

	SHARE_QUOTA_EXCEEDED: StatusCodes.TOO_MANY_REQUESTS,
	RATE_LIMIT_EXCEEDED: StatusCodes.TOO_MANY_REQUESTS,

	EGRESS_LIMIT_REACHED: StatusCodes.SERVICE_UNAVAILABLE,
	QBITTORRENT_UNAVAILABLE: StatusCodes.INTERNAL_SERVER_ERROR,
	INTERNAL_ERROR: StatusCodes.INTERNAL_SERVER_ERROR,
} as const;

export type ErrorCodeName = keyof typeof ErrorCode;
